### ISSUE TITLE
Missing test data

### ISSUE THREAD

**Issue by pcm32** [ebi-gene-expression-group/garnett-cli#14]
Hi @a-solovyev12 , I hope that you're doing well, I'm guessing that you would have this file: https://github.com/ebi-gene-expression-group/garnett-cli/actions/runs/6277192149/job/17048445723?pr=13#step:4:10 among any old computer around, correct? Thanks!

**Comment by pcm32** [comment]
@pmb59 are you able to access archived EBI accounts? The file above should be in Andrey's ~/public_html directory. It would help me to revive the CI of this github repo.

Thanks!

**Comment by pmb59** [comment]
Hi @pcm32 Personal web spaces at http://www.ebi.ac.uk/~USERNAME have been retired. I'll ask IT if the file is still somewhere

**Comment by pmb59** [comment]
@pcm32 I found the file and I added it here https://github.com/ebi-gene-expression-group/garnett-cli/pull/13  Let me know if that helps

**Comment by pcm32** [comment]
Thanks @pmb59 , you rock! I can take it from there.
